user, tweetの取得用API追加
tanapiyo/reactjs-atomicdesign-sample pull request #1
Opened 2019-12-04 16:47 UTC by tanapiyo

バックエンド側なので本質的ではないですが、Djangoの簡単なセットアップをしました。
・Userモデル
・Tweetモデル
を作っており、ローカルでサーバを立ち上げてリクエストを送ると、json形式で取得ができます。（とりあえず一覧表示用です）

2019-12-04 20:34 UTC, BumpeiShimada commented on backend/tweet/tweet/.gitignore
> +db.sqlite3
`backend/tweet` ディレクトリにも .gitignore がありましたが、こちらにもう一つ置く意味はあるのでしょうか？
(Django 特有の何かがあるのでしたら無視して下さって大丈夫です)

2019-12-04 20:35 UTC, BumpeiShimada commented on backend/tweet/twitter/.gitignore
> +db.sqlite3
同上です

2019-12-04 20:46 UTC, BumpeiShimada requested changes

2019-12-04 20:46 UTC, BumpeiShimada commented on backend/document/API作るメモ.md
> +
全体通してですが、バックエンドの実装を同じレポジトリにしている理由は何でしょうか？
開発の都合上基本的にはそれぞれ別のレポジトリにした方が都合が良いため、基本どの現場でもそうしています。なので特段理由がなければこの段階で分けてしまったほうがいいと思います。

2019-12-05 00:59 UTC, tanapiyo commented on backend/tweet/tweet/.gitignore
> +db.sqlite3
同様に、削除しました！

2019-12-05 00:59 UTC, tanapiyo commented on backend/tweet/twitter/.gitignore
> +db.sqlite3
同様に、削除しました！

2019-12-05 01:00 UTC, tanapiyo commented on backend/document/API作るメモ.md
> +
練習用でレポジトリを1つにしたかったので1つにしておりました。
> 開発の都合上基本的にはそれぞれ別のレポジトリにした方が都合が良いため、基本どの現場でもそうしています。
とのことだったので、分けました。backendの方もコラボレーターにしておりますので、ご確認いただければと思います！

2019-12-05 01:42 UTC, BumpeiShimada approved these changes

2019-12-05 01:47 UTC, BumpeiShimada commented on backend/tweet/tweet/.gitignore
> +db.sqlite3
プルリクエスト見る限り消えていなかったです🤔
プッシュをし忘れていたり、違うブランチにプッシュしてしまったりしていませんか？

2019-12-05 01:52 UTC, BumpeiShimada commented
Django の方見ましたが、問題ありませんでした。
このプルリクはもう必要ないので、クローズしておくと後々不要なものがプルリク一覧に出てこなくなるので良いと思います :) (同様の理由で、フィーチャーブランチも消しておくといいと思います)

2019-12-08 12:56 UTC, merged